
import { GoogleGenAI, Modality } from "@google/genai";
import { ImageData } from '../types';

export const editImage = async (baseImage: ImageData, prompt: string): Promise<string> => {
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
        throw new Error("API_KEY is not configured. Please set up your environment variables.");
    }
    // API key is read from environment variables
    const ai = new GoogleGenAI({ apiKey });

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    {
                        inlineData: {
                            data: baseImage.data,
                            mimeType: baseImage.mimeType,
                        },
                    },
                    {
                        text: prompt,
                    },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        // The Gemini 2.5 Flash Image model should return an image.
        // We look for the first part that has inlineData.
        for (const part of response.candidates?.[0]?.content?.parts ?? []) {
            if (part.inlineData) {
                return part.inlineData.data; // This is the base64 encoded image string
            }
        }

        throw new Error("No image was generated by the API. The response may have been blocked or contain no image data.");
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
        // Avoid leaking raw API error details to the user, but provide a helpful message.
        if (errorMessage.includes('API_KEY')) {
             throw new Error('Failed to generate image due to an API key issue. Please check your configuration.');
        }
        throw new Error(`Failed to generate image. ${errorMessage}`);
    }
};